// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABKDQ0v37tOd9YeBnIIIvUeaGB6ulLHD4',
    appId: '1:261449283422:web:3cc2c382e2445211c341cf',
    messagingSenderId: '261449283422',
    projectId: 'fire-itsqmet',
    authDomain: 'fire-itsqmet.firebaseapp.com',
    storageBucket: 'fire-itsqmet.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpifJsze2Ih-vNR9tYsq_yRuPHGpWoals',
    appId: '1:261449283422:android:944b74143a0546e6c341cf',
    messagingSenderId: '261449283422',
    projectId: 'fire-itsqmet',
    storageBucket: 'fire-itsqmet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe4lnYt6h-dU8kRZtG2KKTqbfzXw-Xrts',
    appId: '1:261449283422:ios:deef1a9297865cafc341cf',
    messagingSenderId: '261449283422',
    projectId: 'fire-itsqmet',
    storageBucket: 'fire-itsqmet.appspot.com',
    iosBundleId: 'com.example.taller1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe4lnYt6h-dU8kRZtG2KKTqbfzXw-Xrts',
    appId: '1:261449283422:ios:deef1a9297865cafc341cf',
    messagingSenderId: '261449283422',
    projectId: 'fire-itsqmet',
    storageBucket: 'fire-itsqmet.appspot.com',
    iosBundleId: 'com.example.taller1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABKDQ0v37tOd9YeBnIIIvUeaGB6ulLHD4',
    appId: '1:261449283422:web:9c1cfda73895716bc341cf',
    messagingSenderId: '261449283422',
    projectId: 'fire-itsqmet',
    authDomain: 'fire-itsqmet.firebaseapp.com',
    storageBucket: 'fire-itsqmet.appspot.com',
  );

}